# Generated by Django 6.0.6 on 2026-06-16 14:46

import app.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('nombre', models.CharField(max_length=150)),
                ('rol', models.CharField(choices=[('artista', 'Artista'), ('organizador', 'Organizador')], max_length=20)),
                ('email_verificado', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_artistico', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('numero_telefono', models.CharField(max_length=20)),
                ('ciudad', models.CharField(db_index=True, max_length=100)),
                ('descripcion_profesional', models.TextField()),
                ('documento_identidad', models.FileField(upload_to='artistas/documentos/', validators=[app.models.validar_documento])),
                ('foto_perfil', models.ImageField(upload_to='artistas/perfiles/', validators=[app.models.validar_foto_perfil])),
                ('disciplina', models.CharField(choices=[('musica', 'Música'), ('danza', 'Danza'), ('teatro', 'Teatro'), ('magia', 'Magia'), ('circo', 'Circo'), ('pintura', 'Pintura'), ('fotografia', 'Fotografía'), ('stand_up', 'Stand Up'), ('canto', 'Canto'), ('dj', 'DJ'), ('otro', 'Otro')], db_index=True, max_length=50)),
                ('anios_experiencia', models.PositiveIntegerField()),
                ('tarifa_por_hora', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tarifa_por_evento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('incluye_traslado', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_artista', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Artista',
                'verbose_name_plural': 'Artistas',
            },
        ),
        migrations.CreateModel(
            name='FotoArtista',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('foto', models.ImageField(upload_to='artistas/fotos/', validators=[app.models.validar_foto_galeria])),
                ('orden', models.PositiveIntegerField(default=0)),
                ('subido_en', models.DateTimeField(auto_now_add=True)),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='app.artista')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Organizador',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('telefono', models.CharField(max_length=20)),
                ('profesion_o_empresa', models.CharField(db_index=True, max_length=200)),
                ('descripcion_breve', models.TextField(max_length=500)),
                ('documento_identidad', models.FileField(upload_to='organizadores/documentos/', validators=[app.models.validar_documento])),
                ('foto_perfil', models.ImageField(upload_to='organizadores/perfiles/', validators=[app.models.validar_foto_perfil])),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_organizador', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Organizador',
                'verbose_name_plural': 'Organizadores',
            },
        ),
        migrations.CreateModel(
            name='VideoArtista',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('video', models.FileField(upload_to='artistas/videos/', validators=[app.models.validar_video])),
                ('titulo', models.CharField(blank=True, max_length=200)),
                ('subido_en', models.DateTimeField(auto_now_add=True)),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='app.artista')),
            ],
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['email'], name='app_usuario_email_00f306_idx'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['rol'], name='app_usuario_rol_db79e1_idx'),
        ),
        migrations.AddIndex(
            model_name='artista',
            index=models.Index(fields=['ciudad', 'disciplina'], name='app_artista_ciudad_4aecb5_idx'),
        ),
        migrations.AddIndex(
            model_name='artista',
            index=models.Index(fields=['nombre_artistico'], name='app_artista_nombre__cb241f_idx'),
        ),
        migrations.AddIndex(
            model_name='fotoartista',
            index=models.Index(fields=['artista', 'orden'], name='app_fotoart_artista_0e3dc6_idx'),
        ),
        migrations.AddIndex(
            model_name='organizador',
            index=models.Index(fields=['profesion_o_empresa'], name='app_organiz_profesi_4ce507_idx'),
        ),
        migrations.AddIndex(
            model_name='videoartista',
            index=models.Index(fields=['artista'], name='app_videoar_artista_50ee7c_idx'),
        ),
    ]
